function openTab(evt,cityName){var i,tabcontent,tablinks;tabcontent=document.getElementsByClassName("tabcontent");for(i=0;i<tabcontent.length;i++){tabcontent[i].style.display="none"}
tablinks=document.getElementsByClassName("tablinks");for(i=0;i<tablinks.length;i++){tablinks[i].className=tablinks[i].className.replace(" active","")}
document.getElementById(cityName).style.display="block";evt.currentTarget.className+=" active"}
$(document).ready(function(){if($(".book_content").length>0){$(".book_content").prepend("<hr style='margin-top: 0px !important; width: 30%; border-top: 1px solid black; position: relative; margin-left: 0px !important'></hr>");if($("h4").length>0){$(".book_content h3").append("<hr style='width: 30%; border-top: 1px solid black; position: relative; margin-left: 0px !important'></hr>")}}
$(".book-module").hover(function(){$(this).css("background-color","#EEEEEE")},function(){$(this).css("background-color","#F5F5F5")});$(".collapse-link").click(function(e){$(this).closest(".panel-heading").find(".panel-title").first().toggleClass("collapsed")});if($().tooltip!==undefined){$('[data-toggle="tooltip"]').tooltip()}
$("#rankingModal").css("display","none");$('.level-icon-wrapper a').click(function(){('#rankingModal').css("display","block")});$('.catalog-cards .Disabled a.bx--btn').attr('href','#');if($().modal!==undefined){$(".site-messages").modal("show")}});jQuery(function(){M.util.js_pending('theme_boost/loader');require(['theme_boost/loader','theme_boost/drawer'],function(Loader,Drawer){Drawer.init();M.util.js_complete('theme_boost/loader')});$('.bx--breadcrumb').insertAfter('.bnav-tab')});$(document).ready(function(){if($("#quiz-timer-wrapper").length>0){$(".module_name").remove()}
if($('#intro').length>0||$('#workshop-viewlet-intro').length>0||window.location.href.indexOf("/mod/subcourse")!=-1||window.location.href.indexOf("/mod/facetoface")!=-1||window.location.href.indexOf("/mod/questionnaire")!=-1||window.location.href.indexOf("/mod/feedback")!=-1){var moduleIntro=$('.module_intro')}
var noOverflowDiv=$('.module_intro').next('.no-overflow');if(noOverflowDiv.length>0&&$('div[role="main"] h2:first').length>0){noOverflowDiv.insertAfter($('div[role="main"] h2:first'))}
if($(".topics_sla").length>0){$(".block_course_modulenavigation").hide();if($(".block_settings").length==0){$(".leftnav").hide();$('#main_content_course').removeClass('bx--col-lg-7').addClass('bx--col-lg-9');$('#main_content_course').removeClass('bx--col-lg-8').addClass('bx--col-lg-12');$(".summarytext div:contains('Turn editing on')").remove()}}
if(window.location.href.indexOf("/course/view")!=-1&&$('.block_acclaim').length>0&&$(".topics_sla").length==0&&$(".block_acclaim").find("img").length>0){function callCheckAcclaimLoad(acclaimUser){return new Promise((resolve,reject)=>{if(acclaimUser!="1"){$(".notification_course_credly").removeAttr("hidden");$("#main_content").hide();$(".block_acclaim").hide();$(".block_course_modulenavigation").hide();var credlyInterval=setInterval(function(){callCheckAcclaim()},5000);$(".credly_skip").click(function(){clearInterval(credlyInterval);$(".notification_course_credly").hide();$("#main_content").show();$(".block_acclaim").show();$(".block_course_modulenavigation").show()});resolve()}else{reject('acclaimUser is 1')}})}
callCheckAcclaimLoad(acclaimUser).then(()=>{console.log('Promise resolved')}).catch((error)=>{console.error(error)}).finally(()=>{console.log('Removing skeleton state');$(".bx--skeleton").removeClass("bx--skeleton")});function callCheckAcclaim(){$.ajax({type:"GET",dataType:"text",url:`${window.location.origin}/blocks/acclaim/checkAcclaim.php`,success:function(data){console.log(data.indexOf("true"));if(data.indexOf("true")!=-1){$.ajax({type:"GET",dataType:"text",url:`${window.location.origin}/theme/dlpcarbon/force_logout.php`,success:function(data){console.log(data.indexOf("credly user properly set!"));location.reload()},error:function(xhr,status,error){alert(error)}})}},error:function(xhr,status,error){alert(error)}})}}else{if($(".topics_sla").length==0){$(".bx--skeleton").removeClass("bx--skeleton")}}
$('#language-select').change(function(){var url=$(this).val();if(url){window.location=url}});$("#close_notification").click(function(){var courseid=$("#not_courseid").attr('value');var userid=$("#not_userid").attr('value');$.ajax({url:"/theme/dlpcarbon/close_notification.php",type:"POST",data:{courseid:courseid,userid:userid,},success:function(data){$("#close_notification").parent().remove()},})});if($(".block_course_modulenavigation").length>0){if($(".block_course_modulenavigation").find('.d-inline').length==0){$(".badge_message").remove()}}
if($(".block_settings").length==0){$(".badge_message").remove()}else if($(".block_settings").length==1){$(".notification_course").remove()}});$(document).ready(function(){var copyButton=$('.bx--copy-btn');copyButton.on('click',function(){var codeSnippet=$('.bx--snippet-container').text().trim();var tempInput=$('<input>');tempInput.val(codeSnippet);$('body').append(tempInput);tempInput.select();document.execCommand('copy');tempInput.remove();$('.bx--assistive-text').text('Copied!')})});$(document).ready(function(){$('#completion-progress').wrap('<div style="overflow-x: auto;"></div>')});$(document).ready(function(){if(window.location.href.indexOf("report/completion/")>-1){$("div[role='main']").css("overflow","auto")}
$(".revalidate_submit").click(function(){$(".modal-revalidate").modal('show')});$("#button_reset_completions").click(function(){var wls_userid=$("#wls_userid").val();var wls_coursecode=$("#wls_coursecode").val();$.ajax({url:"/local/wlsbridge/revalidate_course.php",type:"POST",data:{wls_userid:wls_userid,wls_coursecode:wls_coursecode,action:"reset"},beforeSend:function(){$("#overlay").show()},success:function(data){$("#overlay").hide();location.reload()},error:function(){$("#overlay").hide()}})});if(window.location.href.indexOf("/mod/")==-1&&window.location.href.indexOf("/course/")==-1){$(".block_course_modulenavigation").remove()}
if(window.location.href.indexOf("/accesscontrol/")!==-1&&$(".block_settings").length==0){$(".leftnav").remove();$(".bx--col-lg-9").addClass("bx--col-lg-12").removeClass("bx--col-lg-9")}
if(window.location.href.indexOf("/quiz/attempt")!=-1){$(".leftnav").css("background-color","white");$(".right-nav-blocks").attr('style','margin-top: 0px !important');$("#activity-prevnext").remove()}
if(window.location.href.indexOf("/report/stats/")!=-1){if($(".lastrow").length>0){if($(".lastrow").length>1){$(".lastrow").eq(1).removeClass('lastrow')}
$(".lastrow").css("display","grid")}}
if(window.location.href.indexOf("course/edit")!=-1){if($("#fitem_id_hiddensections").length>0){$("#fitem_id_hiddensections").remove()}}
$(".sitetopic").append($(".block_enrollmentkey"));$(".sitetopic").append($(".block_ibmmyenrols"));if($("#settingsnav").length==0||($(".role-student").length>0&&$(".meta").length>0&&$(".role").length>0)&&$(".format-topics").length==0){if($(".ishidden").length>0){$(".ishidden").parent().parent().parent().remove()}}
if($(".role-student").length==1){$(".block_settings").remove()}
if($(".role-student").length>0&&$(".meta").length>0&&$(".role").length>0){console.log('test 2');$(".block_course_modulenavigation").find($(".card-title")).remove();$(".summarytext div:contains('Turn editing on')").remove()}
if($(".block_navigation").length>0){$(".block_navigation").remove()}
$(".block_settings").append($(".block_adminblock"));$(".path-course-view .completionprogress").detach().appendTo('.progress-outer');$('h3.sectionname, span.sectionname, .summarytext').find('br').remove();function onlySpaces(str){return str.trim().length===0}
if(!onlySpaces($('#section-0').find(".sectionname").text())){$('#section-0 .content .sectionname').css('margin-top','+=15px');$('#section-0 .content .sectionname').css('margin-bottom','+=25px')}
if(!onlySpaces($('#section-0 .content .summarytext').find(".no-overflow").text())){$('body:not(.editing) #section-0 .content .summarytext .no-overflow').css('padding-top','+=3%')}
if(onlySpaces($('#section-0 .content .sectionname').find(".no-overflow").text())){$('body:not(.editing) #section-0 .content .summarytext .no-overflow').css('padding-top','-=55px')}});window.onload=function(){var down_arrow_svg='<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg>';var up_arrow_svg='<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 11.354a.5.5 0 0 1 .708 0L8 5.707l5.646 5.647a.5.5 0 0 1 .708-.708l-6-6a.5.5 0 0 1-.708 0l-6 6a.5.5 0 0 1 0 .708z"/></svg>';$('.accordionExample').on('hidden.bs.collapse',function(e){$(e.target).prev('.card-h').find('.accordion-arrow').html(down_arrow_svg)});$('.accordionExample').on('shown.bs.collapse',function(e){$(e.target).prev('.card-h').find('.accordion-arrow').html(up_arrow_svg)})};document.addEventListener('DOMContentLoaded',function(){var links=document.getElementsByClassName('no-propagation');for(var i=0;i<links.length;i++){links[i].addEventListener('click',function(event){event.stopPropagation()})}});$(document).ready(function(){console.log("Document ready. Preparing to access iframe...");const iframe=document.querySelector(".h5p-iframe");if(!iframe){console.log("Iframe not found.");return}
iframe.addEventListener("load",function(){console.log("Iframe loaded. Attempting to access iframe content...");const iframeDoc=iframe.contentDocument||iframe.contentWindow.document;if(!iframeDoc||iframeDoc.readyState!=="complete"){console.log("Iframe content is not fully accessible or ready.");return}
console.log("Iframe document fully loaded. Waiting for draggable elements...");const checkForDraggables=setInterval(()=>{const draggableElements=$(iframeDoc).find(".ui-draggable");if(draggableElements.length>0){console.log(`Found ${draggableElements.length} draggable elements. Capturing original texts...`);const originalTexts={};draggableElements.each(function(index){const element=$(this);const firstSpan=element.find("span:first");const fullText=firstSpan.length?firstSpan.text().trim():element.text().trim();if(fullText){originalTexts[index]=fullText;console.log(`Captured original text for draggable ${index}: "${fullText}"`)}else{console.warn(`Draggable ${index} has empty or undefined text.`)}});setInterval(()=>{draggableElements.each(function(index){const element=$(this);const firstSpan=element.find("span:first");const originalText=originalTexts[index];const currentText=firstSpan.length?firstSpan.text().trim():element.text().trim();console.log(`Checking text for draggable ${index}: currentText = "${currentText}", originalText = "${originalText}"`);if(currentText.includes("...")&&currentText!==originalText){console.log(`Detected truncation on draggable ${index}. Restoring text.`);if(firstSpan.length){firstSpan.text(originalText)}else{element.text(originalText)}
console.log(`Text restored for draggable ${index} to: "${originalText}"`)}});$(iframeDoc).find(".ui-droppable").each(function(){$(this).css("cssText","width: auto !important;")});console.log("Set width to auto for all .ui-droppable elements.")},500);clearInterval(checkForDraggables)}else{console.log("Draggable elements not found yet. Retrying...")}},500)})});$(document).ready(function(){if(window.location.href.indexOf("course/modedit.php")>-1){$("[id^='action-menu-']").each(function(){const idNumber=parseInt(this.id.split('-').pop(),10);if(idNumber>1){$(this).hide()}});$("#action-menu-toggle-0").hide()}
if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){$(".activity-item .activity-info, .activity-item .activity-actions .automatic-completion-conditions .badge .icon").each(function(){$(this).attr("style","margin-left: -280px !important;")});$(".right-nav-blocks-course").each(function(){$(this).attr("style","max-width: 100% !important;")});$(".leftnav").each(function(){$(this).attr("style","max-width: 100% !important;")})}
if($("#block-region-side-pre").children('section').length==0){$('.bx--col-lg-9').removeClass('bx--col-lg-9').addClass('bx--col-lg-12')}
if($("#no_credly").length>0){$("#credly_notif_3").removeAttr("hidden");$("#credly_notif_1").hide();$("#credly_notif_2").hide()}
if(window.location.href.indexOf("/mod/certificate")==-1||window.location.href.indexOf("/mod/scorm")==-1||window.location.href.indexOf("/mod/book")==-1){if($(".module_intro").length>0){$("[id$='intro']").remove()}}
if(window.location.href.indexOf("/mod/questionnaire")!=-1){$(".qn-legend").find(".no-overflow").remove()}
if(window.location.href.indexOf("/mod/feedback")!=-1){$(".feedback_description").find(".no-overflow").remove()}
if(window.location.href.indexOf("/mod/facetoface")!=-1){$("#description").remove()}
$('iframe').each(function(){if($(this).attr('src')&&$(this).attr('src').includes('/mod/hvp/')){if($(this).attr('id')==='kaltura_player'){$(this).removeAttr('id')}}});if(window.location.pathname=="/"||window.location.pathname=="/index.php"){$.ajax({url:'/theme/dlpcarbon/check_session.php',type:'GET',success:function(data){if(data.indexOf("No course to redirect")===-1){window.location.href=data}},error:function(request,error){console.log("Request: "+JSON.stringify(request))}})}});if(window.location.href.indexOf("/admin/tool/installaddon/")==-1){function transformIframeToGenerico(){$('.editor_atto_content_wrap').each(function(){$(this).find('iframe').each(function(){var $iframe=$(this);var src=$iframe.attr('src')||'';var width=$iframe.attr('width')||'560';var height=$iframe.attr('height')||'315';var frameborder=$iframe.attr('frameborder')||'0';var allowfullscreen=$iframe.attr('allowfullscreen')?'allowfullscreen=""':'';var id=$iframe.attr('id')||'';var genericoAttributes=['type="iframe"','src="'+src+'"','width="'+width+'"','height="'+height+'"','frameborder="'+frameborder+'"'];if(id)genericoAttributes.push('id="'+id+'"');if(allowfullscreen)genericoAttributes.push(allowfullscreen);var genericoTemplate='{GENERICO:'+genericoAttributes.join(', ')+'}';$iframe.replaceWith(genericoTemplate)})})}
function sanitizeAttoText(){if($("#user_edit")){var $editorContent=$('.editor_atto_content_wrap');if($editorContent.length>0){var plainText=$editorContent.text();plainText=plainText.replace(/\{\{[^}]*\}\}/g,'');plainText=plainText.replace(/\[\[[^\]]*\]\]/g,'');$editorContent.html(plainText)}}}
function transformImageToGenerico(){$('.editor_atto_content_wrap').each(function(){$(this).find('img').each(function(){var $img=$(this);var src=$img.attr('src')||'';var width=$img.attr('width')||'';var height=$img.attr('height')||'';var className=$img.attr('class')||'';var style=$img.attr('style')||'';var url=new URL(src,window.location.origin);var dataLink=url.pathname+url.search;var genericoAttributes=['type="image"','src="'+src+'"','width="'+width+'"','height="'+height+'"','class="'+className+'"','style="'+style+'"','link="'+dataLink+'"'];var genericoTemplate='{GENERICO:'+genericoAttributes.join(' ')+'}';$img.replaceWith(genericoTemplate)})})}
function transformFormToLink(){$('.editor_atto_content_wrap').each(function(){$(this).find('form').each(function(){var $form=$(this);if($form.find('input[type="submit"][value="Launch"]').length>0){var action=$form.attr('action')||'';var $link=$('<a>',{text:'Launch',href:action,class:'btn btn-primary'});$form.replaceWith($link)}})})}
function transformDivsToGenerico(){$('.editor_atto_content_wrap').each(function(){$(this).find('div:contains("Go to the next course")').filter(function(){return $(this).text().trim().includes("Go to the next course")}).each(function(){var $div=$(this);var onClickAttr=$div.attr('onclick')||'';var urlMatch=onClickAttr.match(/location(?:\.href)?='([^']+)'/)||[];var courseUrl=urlMatch[1]||'';if(courseUrl){var genericoTemplate='{GENERICO:type="custombutton_next", course_url="'+courseUrl+'"}';$div.replaceWith(genericoTemplate)}});var returnButtonFilters=[{text:"Return to the learning plan",type:"plan"},{text:"Return to the learning path",type:"path"}];returnButtonFilters.forEach(function(filter){$(this).find('div:contains("'+filter.text+'")').filter(function(){return $(this).text().trim().includes(filter.text)}).each(function(){var $div=$(this);var onClickAttr=$div.attr('onclick')||'';var urlMatch=onClickAttr.match(/location(?:\.href)?='([^']+)'/)||[];var planUrl=urlMatch[1]||'';if(planUrl){var genericoTemplate='{GENERICO:type="custombutton_return", text="'+filter.type+'", plan_url="'+planUrl+'"}';$div.replaceWith(genericoTemplate)}})},this)})}
var ids=['#id_saveanddisplay','#id_submitbutton','#id_submitbutton2',"#save","#id_clone_item","#id_update_item"];ids.forEach(function(id){var isClicked=!1;$(id).on('click',function(e){if(!isClicked){e.preventDefault();if($(".block_settings").length==0){}
if($('.CodeMirror').length>0){$('.editor_atto .atto_html_button').trigger('click');if($(".block_settings").length==0){}
setTimeout(function(){isClicked=!0;$(id).trigger('click')},1000)}else{if($(".block_settings").length==0){}
setTimeout(function(){isClicked=!0;$(id).trigger('click')},1000)}}})})};$(window).on('load',function(){$('iframe').each(function(){if($(this).attr('src')&&$(this).attr('src').includes('/mod/hvp/')||$(this).attr('src')&&$(this).attr('src').includes('/h5p/')){if($(this).attr('id')==='kaltura_player'){$(this).removeAttr('id')}}})});$(window).on('load',function(){var greenCheckmarkImages=$(".badge.alert-success img.icon[src$='completion-auto-enabled-green']");console.log("Number of green checkmark images found: "+greenCheckmarkImages.length);greenCheckmarkImages.each(function(index,element){var instanceName=$(element).closest('.activity-item').data('activityname');console.log("Instance Name: "+instanceName);var correspondingListItem=$("li:has(.activityname:contains('"+instanceName+"'))");var hasSquareClass=correspondingListItem.find('.far.fa-square.black-link').length;if(hasSquareClass>0){$(element).remove()}});$('.editor_atto_content_wrap').each(function(){var $wrap=$(this);var content=$wrap.children().html();var updatedContent=content;updatedContent=updatedContent.replace(/{GENERICO:[^}]*type\s*=\s*"iframe"[^}]*}/g,function(match){var width=match.match(/width\s*=\s*"([^"]*)"/)||[];var height=match.match(/height\s*=\s*"([^"]*)"/)||[];var src=match.match(/src\s*=\s*"([^"]*)"/)||[];var frameborder=match.match(/frameborder\s*=\s*"([^"]*)"/)||[];var allowfullscreen=match.match(/allowfullscreen\s*=\s*"([^"]*)"/)||[];var id=match.match(/id\s*=\s*"([^"]*)"/)||[];return'<iframe src="'+(src[1]||'')+'" width="'+(width[1]||'560')+'" height="'+(height[1]||'315')+'" frameborder="'+(frameborder[1]||'0')+'" '+(allowfullscreen[1]?'allowfullscreen':'')+(id[1]?' id="'+id[1]+'"':'')+'></iframe>'});updatedContent=updatedContent.replace(/{GENERICO:[^}]*type\s*=\s*"image"[^}]*}/g,function(match){var src=match.match(/src\s*=\s*"([^"]*)"/)||[];var width=match.match(/width\s*=\s*"([^"]*)"/)||[];var height=match.match(/height\s*=\s*"([^"]*)"/)||[];var className=match.match(/class\s*=\s*"([^"]*)"/)||[];var style=match.match(/style\s*=\s*"([^"]*)"/)||[];var imgTag='<img src="'+(src[1]||'')+'"';if(width[1]){imgTag+=' width="'+width[1]+'"'}
if(height[1]){imgTag+=' height="'+height[1]+'"'}
if(className[1]){imgTag+=' class="'+className[1]+'"'}
if(style[1]){imgTag+=' style="'+style[1]+'"'}
imgTag+=' />';return imgTag});updatedContent=updatedContent.replace(/{GENERICO:[^}]*type\s*=\s*"formbutton"[^}]*}/g,function(match){var formlink=match.match(/formlink\s*=\s*"([^"]*)"/)||[];return'<a href="'+(formlink[1]||'#')+'" class="btn btn-primary">Launch</a>'});updatedContent=updatedContent.replace(/{GENERICO:[^}]*type\s*=\s*"custombutton_next"[^}]*}/g,function(match){var course_url=match.match(/course_url\s*=\s*"([^"]*)"/)||[];return'<div style="display: inline-block; padding: 15px; margin: 10px 5px 5px 0px; background-color: rgb(15, 98, 254); color: rgb(255, 255, 255); cursor: pointer;" onmouseover="this.style.backgroundColor=\'#0B4AC0\'" onmouseout="this.style.backgroundColor=\'#0F62FE\'" onclick="location.href=\''+(course_url[1]||'#')+'\';">Go to the next course <svg ...></svg></div>'});updatedContent=updatedContent.replace(/{GENERICO:[^}]*type\s*=\s*"custombutton_return"[^}]*}/g,function(match){var plan_url=match.match(/plan_url\s*=\s*"([^"]*)"/)||[];var text=match.match(/text\s*=\s*"([^"]*)"/)||[];return `<div style="display: inline-block; margin: 10px 5px 5px 0px; background: none; color: rgb(15, 98, 254); border: 1px solid rgb(15, 98, 254); cursor: pointer; padding: 15px; fill: white;" onmouseover="this.style.background='#0f62fe';this.style.color='white';icon.style.fill='white';" onmouseout="this.style.background='none';this.style.color='#0f62fe';icon.style.fill='#0f62fe';" onclick="location.href='${plan_url[1] || '#'}';">Return to the learning ${text[1] || 'path'} <svg id="icon" ...></svg></div>`});$wrap.children().html(updatedContent)})});$(document).ready(function(){setInterval(function(){if($(".atto_stash_button").length==0||$("#user_edit").length>0){$(".atto_generico_button_iconone").remove();$(".atto_html_button").remove()}},1000);$('.automatic-completion-conditions').each(function(){let danger_count=$(this).find('span.badge.badge-pill.alert-danger').length;if(danger_count>0){$(this).find('span.badge.badge-pill.alert-success.icon-no-margin').remove();return}
$(this).find('span.badge.badge-pill.alert-success.icon-no-margin:gt(0)').remove()})})